credentials:
  login_name: "chengjun.jiang"
  password: "shanghai0303"
  login_type_id: "2"
  univ_code: "RC00001"

browser:
  headless: False
  timeout: 30
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0"
  window_size:
    width: 1920
    height: 1080
  exec_path: ""
  proxy: ""
